import os
import numpy as np
import torch
import torchaudio
from kokoro import KPipeline

# --- CONFIGURATION ---
# The text you want to generate
TEXT_TO_GENERATE = "Managing type 1 diabetes (T1D) involves balancing insulin, carbohydrate intake, blood glucose monitoring, and physical activity. Because the pancreas no longer produces insulin, individuals must administer it daily via injections or an insulin pump to convert food into energy and maintain target blood sugar levels."
# The voice to use (e.g., af_heart, af_bella, am_adam)
VOICE_NAME = "am_michael"
# The target directory
OUTPUT_DIR = r"C:\Users\SHREY\Desktop\MuseTalk\inference\sample"
# The output filename
OUTPUT_FILENAME = "generated_audio.wav"
# Target sample rate (16kHz mono as requested)
TARGET_SAMPLE_RATE = 16000
# Kokoro default sample rate is 24000
KOKORO_SAMPLE_RATE = 24000
# ---------------------

def generate_audio():
    print(f"Initializing Kokoro Pipeline with voice: {VOICE_NAME}")
    # lang_code 'a' for American English
    pipeline = KPipeline(lang_code='a') 
    
    print(f"Generating audio for text: \"{TEXT_TO_GENERATE}\"")
    generator = pipeline(
        TEXT_TO_GENERATE,
        voice=VOICE_NAME,
        speed=1.0,
        split_pattern=r"\n+",
    )

    audio_chunks = []
    for _, _, audio in generator:
        if not isinstance(audio, np.ndarray):
            audio = np.array(audio, dtype=np.float32)
        audio_chunks.append(audio)

    if not audio_chunks:
        print("Error: No audio was generated by the pipeline.")
        return

    # Combine chunks into a single array
    full_audio = np.concatenate(audio_chunks)
    
    # Convert to torch tensor for resampling
    # Torchaudio expects shape [channels, time]
    audio_tensor = torch.from_numpy(full_audio).unsqueeze(0)
    
    print(f"Resampling from {KOKORO_SAMPLE_RATE}Hz to {TARGET_SAMPLE_RATE}Hz...")
    resampler = torchaudio.transforms.Resample(orig_freq=KOKORO_SAMPLE_RATE, new_freq=TARGET_SAMPLE_RATE)
    resampled_audio = resampler(audio_tensor)
    
    # Ensure it's mono (should already be [1, T])
    if resampled_audio.shape[0] > 1:
        resampled_audio = torch.mean(resampled_audio, dim=0, keepdim=True)
    
    # Ensure the output directory exists
    if not os.path.exists(OUTPUT_DIR):
        print(f"Creating directory: {OUTPUT_DIR}")
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILENAME)
    
    print(f"Saving 16kHz mono audio to: {output_path}")
    torchaudio.save(output_path, resampled_audio, TARGET_SAMPLE_RATE)
    print("Generation complete!")

if __name__ == "__main__":
    try:
        generate_audio()
    except Exception as e:
        print(f"An error occurred: {e}")
