"""remove_legacy_metrics

Revision ID: 1806f3b72a85
Revises: 6804ddd750d8
Create Date: 2026-06-08 22:55:57.233931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1806f3b72a85'
down_revision: Union[str, Sequence[str], None] = '6804ddd750d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'overall_camera_engagement')
    op.drop_column('interview_sessions', 'average_wpm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('average_wpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('overall_camera_engagement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
