"""initial_schema

Revision ID: 6804ddd750d8
Revises: 
Create Date: 2026-06-08 22:23:56.980311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6804ddd750d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('resume_text', sa.String(), nullable=True),
    sa.Column('resume_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_metrics_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('overall_camera_engagement', sa.Float(), nullable=True),
    sa.Column('average_focus', sa.Float(), nullable=True),
    sa.Column('average_wpm', sa.Float(), nullable=True),
    sa.Column('overall_gaze_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default='{"forward":0,"left":0,"right":0,"down":0,"away":0}', nullable=False),
    sa.Column('total_questions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_evaluation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_sessions')
    op.drop_table('profiles')
    # ### end Alembic commands ###
